language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
before_install:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
  - ls -ll $GPG_DIR
deploy:
  - provider: script
    script: .travis/publish.sh
    skip_cleanup: true
    on:
      repo: cerner/beadledom
      branch: update-release-doc
      jdk: oraclejdk8
  - provider: script
    script: .travis/publish.sh
    skip_cleanup: true
    on:
      repo: cerner/beadledom
      tags: true
      jdk: oraclejdk8
env:
  global:
  - GPG_DIR="`pwd`/.travis"
